# Generated by Django 5.2.15 on 2026-09-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cta',
            name='footer_script',
        ),
        migrations.RemoveField(
            model_name='cta',
            name='header_script',
        ),
    ]
