# Generated by Django 5.2.15 on 2026-09-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='custom_structured_data',
        ),
    ]
