# Generated by Django 5.2.15 on 2026-09-30 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_remove_flexpage_custom_structured_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioitempage",
            name="url_type_preference",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="url_type_preference",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="url_type_preference",
        ),
    ]
