# Generated by Django 5.2.15 on 2026-09-30 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_resourceshowcaseitem_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="has_page",
        ),
    ]
