# Generated by Django 5.2.15 on 2026-09-30 15:03

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_remove_projectpage_has_page"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        default="Untitled",
                        help_text="Title for this item",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description for this item"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional page to link to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ShowcaseItemLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "target",
                    models.CharField(
                        choices=[("_self", "Same Window"), ("_blank", "New Window")],
                        default="_self",
                        max_length=10,
                    ),
                ),
                (
                    "item",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="pages.showcaseitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ShowcasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Optional introduction text for the showcase page",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Showcase Page",
                "verbose_name_plural": "Showcase Pages",
            },
            bases=(
                wagtailcache.cache.WagtailCacheMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Heading for this section", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for this section"
                    ),
                ),
                (
                    "showcase_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase_sections",
                        to="pages.showcasepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="showcaseitem",
            name="section",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pages.showcasesection",
            ),
        ),
    ]
